# Generated by Django 4.2 on 2023-04-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='etiquetas',
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='articulo',
            name='etiquetas',
            field=models.CharField(default='Sin etiquetas', max_length=100),
        ),
    ]
